//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EmpresaEntities : DbContext
    {
        public EmpresaEntities()
            : base("name=EmpresaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_ciudad> tbl_ciudad { get; set; }
        public virtual DbSet<tbl_depto> tbl_depto { get; set; }
        public virtual DbSet<tbl_empresa> tbl_empresa { get; set; }
        public virtual DbSet<tbl_pais> tbl_pais { get; set; }
    
        public virtual ObjectResult<sp_listarEmpresas_Result> sp_listarEmpresas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listarEmpresas_Result>("sp_listarEmpresas");
        }
    
        public virtual ObjectResult<sp_lisarPaisDeptoCiudad_Result> sp_lisarPaisDeptoCiudad(Nullable<int> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lisarPaisDeptoCiudad_Result>("sp_lisarPaisDeptoCiudad", idEmpresaParameter);
        }
    
        public virtual ObjectResult<sp_listarEmpresasSearch_Result> sp_listarEmpresasSearch(string texto)
        {
            var textoParameter = texto != null ?
                new ObjectParameter("texto", texto) :
                new ObjectParameter("texto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_listarEmpresasSearch_Result>("sp_listarEmpresasSearch", textoParameter);
        }
    }
}
