//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresa
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_empresa
    {
        public int idEmpresa { get; set; }
        public string nombreEmpresa { get; set; }
        public string direccionEmpresa { get; set; }
        public string telEmpresa { get; set; }
        public Nullable<System.DateTime> creacionEmpresa { get; set; }
        public Nullable<System.DateTime> modEmpresa { get; set; }
        public Nullable<int> idCiudad { get; set; }
    
        public virtual tbl_ciudad tbl_ciudad { get; set; }
    }
}
