//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresa
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ciudad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ciudad()
        {
            this.tbl_empresa = new HashSet<tbl_empresa>();
        }
    
        public int idCiudad { get; set; }
        public string nombreCiudad { get; set; }
        public Nullable<int> idDepto { get; set; }
    
        public virtual tbl_depto tbl_depto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_empresa> tbl_empresa { get; set; }
    }
}
